# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
# NOTE: Run: winget configure ./deps.configuration.dsc.yaml
# This file sets up redistributables and other dependencies.
properties:
  configurationVersion: 0.1.0
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify minimum OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: '10.0.22000'
  resources:
    - resource: Microsoft.Windows.Developer/DeveloperMode
      directives:
        description: Enable Developer Mode
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft Visual C++ 2010 x86 Redistributable
        allowPrerelease: true
      settings:
        id: Microsoft.VCRedist.2010.x86
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft Visual C++ 2010 x64 Redistributable
        allowPrerelease: true
      settings:
        id: Microsoft.VCRedist.2010.x64
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft Visual C++ 2012 Redistributable
        allowPrerelease: true
      settings:
        id: Microsoft.VCRedist.2012.x86
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft Visual C++ 2012 x64 Redistributable
        allowPrerelease: true
      settings:
        id: Microsoft.VCRedist.2013.x86
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft Visual C++ 2013 Redistributable (x86)
        allowPrerelease: true
      settings:
        id: Microsoft.VCRedist.2013.x86
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft Visual C++ 2015-2022 Redistributable (x64)
        allowPrerelease: true
      settings:
        id: Microsoft.VCRedist.2015+.x64
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft Visual C++ 2015-2019 Redistributable (x86)
        allowPrerelease: true
      settings:
        id: Microsoft.VCRedist.2015+.x86
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft .NET Runtime 6.0.25 (x64)
        allowPrerelease: true
      settings:
        id: Microsoft.DotNet.Runtime.6
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft .NET Runtime 7.0.14 (x64)
        allowPrerelease: true
      settings:
        id: Microsoft.DotNet.Runtime.7
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft Windows Desktop Runtime 6.0.25
        allowPrerelease: true
      settings:
        id: Microsoft.DotNet.DesktopRuntime.6
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft Windows Desktop Runtime 7.0.14
        allowPrerelease: true
      settings:
        id: Microsoft.DotNet.DesktopRuntime.7
        source: winget