# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
# NOTE: Run: winget configure ./dev.configuration.dsc.yaml
# This file sets up the system for development. NOTE: Requires file explorer to be restarted.
properties:
  configurationVersion: 0.1.0
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify minimum OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: '10.0.22000'
  resources:
    - resource: Microsoft.Windows.Developer/DeveloperMode
      directives:
        description: Enable Developer Mode
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: Microsoft.Windows.Developer/TaskBarAlignment
      directives:
        description: Set taskbar alignment to left
        allowPrerelease: true
      settings:
        Alignment: Left # 'Middle'
    - resource: Microsoft.Windows.Developer/ShowSecondsInClock
      directives:
        description: Show seconds in clock
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: Microsoft.Windows.Developer/HideFileExtensions
      directives:
        description: Show file extensions
        allowPrerelease: true
      settings:
        Ensure: Absent
    - resource: Microsoft.Windows.Developer/ShowTaskViewButton
      directives:
        description: Show task view button
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: Microsoft.Windows.Developer/ShowHiddenFiles
      directives:
        description: Show hidden files
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: Microsoft.Windows.Developer/HideTaskBarLabels
      directives:
        description: Never hide task bar labels
        allowPrerelease: true
      settings:
        HideLabels: Never # 'WhenFull', 'Always'
        # Use caution when setting `RestartExplorer: true` as this will force explorer to close.
        RestartExplorer: true # Required to apply changes
    - resource: Microsoft.Windows.Developer/EnableDarkMode
      directives:
        description: Enable dark mode
        allowPrerelease: true
      settings:
        Ensure: Present
        # Use caution when setting `RestartExplorer: true` as this will force explorer to close.
        RestartExplorer: true # Required to apply changes