# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
# NOTE: Run: winget configure ./utils.configuration.dsc.yaml
# This file sets up general tools that I use, like texting apps, browsers and other utilities.
properties:
  configurationVersion: 0.1.0
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify minimum OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: '10.0.22000'
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Todoist
        allowPrerelease: true
      settings:
        id: Doist.Todoist
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Signal
        allowPrerelease: true
      settings:
        id: OpenWhisperSystems.Signal
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Telegram Desktop
        allowPrerelease: true
      settings:
        id: Telegram.TelegramDesktop
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Internet Download Manager
        allowPrerelease: true
      settings:
        id: Tonec.InternetDownloadManager
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install CrystalDiskInfo
        allowPrerelease: true
      settings:
        id: CrystalDewWorld.CrystalDiskInfo
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install HWiNFO64
        allowPrerelease: true
      settings:
        id: REALiX.HWiNFO
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install DisplayFusion
        allowPrerelease: true
      settings:
        id: BinaryFortress.DisplayFusion
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install NanaZip
        allowPrerelease: true
      settings:
        id: M2Team.NanaZip
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install HandBrake
        allowPrerelease: true
      settings:
        id: HandBrake.HandBrake
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install TreeSize Free
        allowPrerelease: true
      settings:
        id: JAMSoftware.TreeSize.Free
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Fluent Reader
        allowPrerelease: true
      settings:
        id: yang991178.fluent-reader
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Sonic Pi
        allowPrerelease: true
      settings:
        id: SonicPi.SonicPi
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Mozilla Firefox
        allowPrerelease: true
      settings:
        id: Mozilla.Firefox
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Thorium (AVX2)
        allowPrerelease: true
      settings:
        id: Alex313031.Thorium.AVX2
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Everything
        allowPrerelease: true
      settings:
        id: voidtools.Everything
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install EverythingToolbar
        allowPrerelease: true
      settings:
        id: stnkl.EverythingToolbar
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install MPC-BE x64
        allowPrerelease: true
      settings:
        id: MPC-BE.MPC-BE
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install PowerToys (Preview) x64
        allowPrerelease: true
      settings:
        id: Microsoft.PowerToys
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install MeshLab
        allowPrerelease: true
      settings:
        id: CNRISTI.MeshLab
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install FortiClient VPN
        allowPrerelease: true
      settings:
        id: Fortinet.FortiClientVPN
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Hack Fonts version 1.6.0
        allowPrerelease: true
      settings:
        id: SourceFoundry.HackFonts
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install MacType
        allowPrerelease: true
      settings:
        id: MacType.MacType
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Nvidia GeForce Experience
        allowPrerelease: true
      settings:
        id: Nvidia.GeForceExperience
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Nvidia PhysX
        allowPrerelease: true
      settings:
        id: Nvidia.PhysX
        source: winget