# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
# NOTE: Don't remove the first line ^^^, it's used by the yaml-language-server to validate the file.
#
# NOTE: THIS IS A COMBINED VERSION OF THE OTHER DSC CONFIGS IN THIS FOLDER.
# 
# NOTE: This requires pre-release `winget` - https://aka.ms/getwingetpreview
#
# NOTE: Ensure nothing else is running, as the command will force restart explorer.exe.
#
# To run: winget configure ./windows.configuration.dsc.yaml --accept-configuration-agreements
# NOTE: Without `--accept-configuration-agreements`, the command will ask you to accept the agreements after it has validated the file. For a long config like this,
# it's better to accept the agreements first, so that the command can run without user interaction. In any case, it is on you to check the file thoroughly 
# before running it.
# NOTE: `allowPrerelease: true` is required as DSC is still in preview.
#
# See ./winget-install-list.txt for the list of installed packages.
#
# TODO: Add npm & python packages to this file.
properties:
  configurationVersion: 0.1.0
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify minimum OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: '10.0.22000'
  resources:
    # NOTE: First, make the system developer friendly
    - resource: Microsoft.Windows.Developer/DeveloperMode
      directives:
        description: Enable Developer Mode
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: Microsoft.Windows.Developer/TaskBarAlignment
      directives:
        description: Set taskbar alignment to left
        allowPrerelease: true
      settings:
        Alignment: Left # 'Middle'
    - resource: Microsoft.Windows.Developer/ShowSecondsInClock
      directives:
        description: Show seconds in clock
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: Microsoft.Windows.Developer/HideFileExtensions
      directives:
        description: Show file extensions
        allowPrerelease: true
      settings:
        Ensure: Absent
    - resource: Microsoft.Windows.Developer/ShowTaskViewButton
      directives:
        description: Show task view button
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: Microsoft.Windows.Developer/ShowHiddenFiles
      directives:
        description: Show hidden files
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: Microsoft.Windows.Developer/HideTaskBarLabels
      directives:
        description: Never hide task bar labels
        allowPrerelease: true
      settings:
        HideLabels: Never # 'WhenFull', 'Always'
        # Use caution when setting `RestartExplorer: true` as this will force explorer to close.
        RestartExplorer: true # Required to apply changes
    - resource: Microsoft.Windows.Developer/EnableDarkMode
      directives:
        description: Enable dark mode
        allowPrerelease: true
      settings:
        Ensure: Present
        # Use caution when setting `RestartExplorer: true` as this will force explorer to close.
        RestartExplorer: true # Required to apply changes
    # NOTE: Install packages
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install PowerShell 7
        allowPrerelease: true
      settings:
        id: Microsoft.PowerShell
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Todoist
        allowPrerelease: true
      settings:
        id: Doist.Todoist
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Signal
        allowPrerelease: true
      settings:
        id: OpenWhisperSystems.Signal
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Telegram Desktop
        allowPrerelease: true
      settings:
        id: Telegram.TelegramDesktop
        source: winget
    # NOTE: Don't install with Discord.Discord.
    # - resource: Microsoft.WinGet.DSC/WinGetPackage
    #   directives:
    #     description: Install Vesktop
    #     allowPrerelease: true
    #   settings:
    #     id: Vencord.Vesktop
    #     source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Discord
        allowPrerelease: true
      settings:
        id: Discord.Discord
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Internet Download Manager
        allowPrerelease: true
      settings:
        id: Tonec.InternetDownloadManager
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install CrystalDiskInfo
        allowPrerelease: true
      settings:
        id: CrystalDewWorld.CrystalDiskInfo
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install HWiNFO64
        allowPrerelease: true
      settings:
        id: REALiX.HWiNFO
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install DisplayFusion
        allowPrerelease: true
      settings:
        id: BinaryFortress.DisplayFusion
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install NanaZip
        allowPrerelease: true
      settings:
        id: M2Team.NanaZip
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install HandBrake
        allowPrerelease: true
      settings:
        id: HandBrake.HandBrake
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install TreeSize Free
        allowPrerelease: true
      settings:
        id: JAMSoftware.TreeSize.Free
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Fluent Reader
        allowPrerelease: true
      settings:
        id: yang991178.fluent-reader
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Sonic Pi
        allowPrerelease: true
      settings:
        id: SonicPi.SonicPi
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Steam
        allowPrerelease: true
      settings:
        id: Valve.Steam
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Mozilla Firefox
        allowPrerelease: true
      settings:
        id: Mozilla.Firefox
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Thorium (AVX2)
        allowPrerelease: true
      settings:
        id: Alex313031.Thorium.AVX2
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Everything
        allowPrerelease: true
      settings:
        id: voidtools.Everything
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install EverythingToolbar
        allowPrerelease: true
      settings:
        id: stnkl.EverythingToolbar
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install MPC-BE x64
        allowPrerelease: true
      settings:
        id: MPC-BE.MPC-BE
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install PowerToys (Preview) x64
        allowPrerelease: true
      settings:
        id: Microsoft.PowerToys
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install MeshLab
        allowPrerelease: true
      settings:
        id: CNRISTI.MeshLab
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install FortiClient VPN
        allowPrerelease: true
      settings:
        id: Fortinet.FortiClientVPN
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Pandoc
        allowPrerelease: true
      settings:
        id: JohnMacFarlane.Pandoc
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install FFmpeg
        allowPrerelease: true
      settings:
        id: Gyan.FFmpeg
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install ImageMagick
        allowPrerelease: true
      settings:
        id: ImageMagick.ImageMagick
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Hack Fonts version 1.6.0
        allowPrerelease: true
      settings:
        id: SourceFoundry.HackFonts
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Oh My Posh version 19.2.1
        allowPrerelease: true
      settings:
        id: JanDeDobbeleer.OhMyPosh
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Starship
        allowPrerelease: true
      settings:
        id: Starship.Starship
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install RipGrep MSVC
        allowPrerelease: true
      settings:
        id: BurntSushi.ripgrep.MSVC
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install GNU Nano
        allowPrerelease: true
      settings:
        id: GNU.Nano
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Nmap
        allowPrerelease: true
      settings:
        id: Insecure.Nmap
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install aria2
        allowPrerelease: true
      settings:
        id: aria2.aria2
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install lf
        allowPrerelease: true
      settings:
        id: gokcehan.lf
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install NTop
        allowPrerelease: true
      settings:
        id: gsass1.NTop
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install fzf
        allowPrerelease: true
      settings:
        id: junegunn.fzf
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install bat
        allowPrerelease: true
      settings:
        id: sharkdp.bat
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install fd
        allowPrerelease: true
      settings:
        id: sharkdp.fd
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install miniserve
        allowPrerelease: true
      settings:
        id: svenstaro.miniserve
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install gsudo v2.4.1-fixnoninteractive
        allowPrerelease: true
      settings:
        id: gerardog.gsudo
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Node.js
        allowPrerelease: true
      settings:
        id: OpenJS.NodeJS
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install tre-command
        allowPrerelease: true
      settings:
        id: ca.duan.tre-command
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install MacType
        allowPrerelease: true
      settings:
        id: MacType.MacType
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Git
        allowPrerelease: true
      settings:
        id: Git.Git
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install GitHub Desktop
        allowPrerelease: true
      settings:
        id: GitHub.GitHubDesktop
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Git LFS version 3.4.0
        allowPrerelease: true
      settings:
        id: GitHub.GitLFS
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install GitHub CLI
        allowPrerelease: true
      settings:
        id: GitHub.cli
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Strawberry Perl (64-bit)
        allowPrerelease: true
      settings:
        id: StrawberryPerl.StrawberryPerl
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft Visual Studio Code (User)
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Julia 1.9.4
        allowPrerelease: true
      settings:
        id: Julialang.Julia
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Python 3.11
        allowPrerelease: true
      settings:
        id: Python.Python.3.11
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Notepad++ (64-bit x64)
        allowPrerelease: true
      settings:
        id: Notepad++.Notepad++
        source: winget
    # NOTE: Optional
    # - resource: Microsoft.WinGet.DSC/WinGetPackage
    #   directives:
    #     description: Install Nvidia GeForce Experience
    #     allowPrerelease: true
    #   settings:
    #     id: Nvidia.GeForceExperience
    #     source: winget
    # - resource: Microsoft.WinGet.DSC/WinGetPackage
    #   directives:
    #     description: Install Nvidia PhysX
    #     allowPrerelease: true
    #   settings:
    #     id: Nvidia.PhysX
    #     source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft Visual C++ 2008 Redistributable
        allowPrerelease: true
      settings:
        id: Microsoft.VCRedist.2008.x86
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft Visual C++ 2010 x86 Redistributable
        allowPrerelease: true
      settings:
        id: Microsoft.VCRedist.2010.x86
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft Visual C++ 2010 x64 Redistributable
        allowPrerelease: true
      settings:
        id: Microsoft.VCRedist.2010.x64
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft Visual C++ 2012 Redistributable
        allowPrerelease: true
      settings:
        id: Microsoft.VCRedist.2012.x86
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft Visual C++ 2012 x64 Redistributable
        allowPrerelease: true
      settings:
        id: Microsoft.VCRedist.2013.x86
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft Visual C++ 2013 Redistributable (x86)
        allowPrerelease: true
      settings:
        id: Microsoft.VCRedist.2013.x86
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft Visual C++ 2015-2022 Redistributable (x64)
        allowPrerelease: true
      settings:
        id: Microsoft.VCRedist.2015+.x64
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft Visual C++ 2015-2019 Redistributable (x86)
        allowPrerelease: true
      settings:
        id: Microsoft.VCRedist.2015+.x86
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft .NET Runtime 6.0.25 (x64)
        allowPrerelease: true
      settings:
        id: Microsoft.DotNet.Runtime.6
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft .NET Runtime 7.0.14 (x64)
        allowPrerelease: true
      settings:
        id: Microsoft.DotNet.Runtime.7
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft Windows Desktop Runtime 6.0.25
        allowPrerelease: true
      settings:
        id: Microsoft.DotNet.DesktopRuntime.6
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft Windows Desktop Runtime 7.0.14
        allowPrerelease: true
      settings:
        id: Microsoft.DotNet.DesktopRuntime.7
        source: winget
